sudo: required

services:
    - docker

branches:
    only:
    - master

before_install:
    - docker pull schmidtw/xmidt.builder.centos6:latest
    - docker run -it -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -d --name build schmidtw/xmidt.builder.centos6 bash
    - env
    - docker exec build git clone https://github.com/Comcast/prometheus-rpms-centos6.git
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_703128d636df_key -iv $encrypted_703128d636df_iv -in keys/RPM-GPG-KEY-comcast-xmidt.private.enc -out keys/RPM-GPG-KEY-comcast-xmidt.private -d; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker cp keys/RPM-GPG-KEY-comcast-xmidt.private build:/RPM-GPG-KEY-comcast-xmidt.private; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker exec build bash -c "gpg --allow-secret-key-import --import /RPM-GPG-KEY-comcast-xmidt.private"; fi'

script:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker exec build bash -c "pushd prometheus-rpms-centos6; ./build_all.sh; popd"; fi'

after_success:
    - docker cp build:/root/rpmbuild/RPMS/x86_64 .
    - BINARY_NAME=`ls x86_64/`

deploy:
  provider: releases
  prerelease: true
  api_key: "$AUTH_TOKEN_BUILD"
  file:
    - x86_64/$BINARY_NAME
    - keys/RPM-GPG-KEY-comcast-xmidt
  skip_cleanup: true
  on:
    condition: "$TRAVIS_PULL_REQUEST = false"

